project:
  type: website

website:
  title: "Dalya Manatova"
  navbar:
    right:
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Talks
        href: talks.qmd
      - text: Teaching & Service
        href: teaching-service.qmd
      - text: CV
        href: cv.qmd

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true
    css: styles.css