project:
  type: website
  resources:
    - CNAME
website:
  title: "Dalya Manatova"
  description: "Dalya Manatova is a postdoctoral researcher at UNC Charlotte studying cybercrime ecosystems, adversarial communities, network science, graph learning, and computational organizational analysis."
  site-url: https://dalya.info
  favicon: files/icon.svg
  open-graph: true
  twitter-card:
    creator: "@dalyapraz"
    image: images/dalya-profile.jpg
  navbar:
    right:
      # - text: Research
      #   href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Talks
        href: talks.qmd
      - text: Teaching & Service
        href: teaching-service.qmd
      - text: CV
        href: cv.qmd

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true
    css: styles.css
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">